apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaces
  labels:
    app: spaces
  namespace: management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spaces
  template:
    metadata:
      labels:
        app: spaces
    spec:
      containers:
      - name: spaces
        image: tedbalashov/exa-spaces:latest
        ports:
        - containerPort: 9002